import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { DialogsProvider } from "@/components/icon/icon";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={inter.className} style={{ backgroundColor: "#000" }}>
        <DialogsProvider>{children}</DialogsProvider>
      </body>
    </html>
  );
}
